# Generated by Django 5.0.8 on 2024-08-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('fullname', models.CharField(blank=True, max_length=100)),
                ('author_list', models.CharField(max_length=500, null=True)),
                ('details', models.TextField(blank=True, max_length=1000, null=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='')),
                ('name', models.CharField(default='', max_length=50)),
                ('form', models.CharField(choices=[('RP', 'restricted-pot'), ('UP', 'unrestricted-pot'), ('SP', 'semirestricted-pot'), ('B', 'bowl'), ('F', 'forno'), ('C', 'cup'), ('J', 'jug'), ('O', 'other'), ('U', 'unknown')], default='U', max_length=2)),
                ('time_start', models.IntegerField(blank=True, null=True)),
                ('time_end', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('language', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('language_code', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('primary_technique', models.CharField(choices=[('C', 'coil'), ('CS', 'coil-spiral'), ('CR', 'coil-ring'), ('S', 'slab'), ('M', 'molded'), ('W', 'wheel'), ('O', 'other'), ('U', 'unknown')], default='U', max_length=20)),
                ('secondary_technique', models.CharField(choices=[('B', 'beating'), ('N', 'none'), ('O', 'other'), ('U', 'unknown')], default='U', max_length=20)),
                ('base_technique', models.CharField(choices=[('B', 'ball'), ('S', 'spiral'), ('SL', 'slab'), ('ST', 'strip'), ('O', 'other'), ('U', 'unknown')], default='U', max_length=20)),
                ('rim_technique', models.CharField(choices=[('R', 'ring'), ('N', 'none'), ('U', 'unknown')], default='U', max_length=20)),
                ('word', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('use', models.CharField(choices=[('B', 'boiling'), ('F', 'frying'), ('FO', 'forno'), ('SE', 'serving'), ('ST', 'storage'), ('SM', 'smoking'), ('C', 'ceremonial'), ('U', 'unknown')], default='U', max_length=20)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('language_family', models.CharField(blank=True, max_length=500, null=True)),
                ('language_superfamily', models.CharField(blank=True, max_length=100, null=True)),
                ('gender_make', models.CharField(choices=[('W', 'women'), ('M', 'men'), ('B', 'both'), ('U', 'unknown')], default='U', max_length=7)),
                ('gender_decorate', models.CharField(choices=[('W', 'women'), ('M', 'men'), ('B', 'both'), ('U', 'unknown')], default='U', max_length=7)),
                ('temper', models.BooleanField(blank=True, null=True)),
                ('decoration_plain', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('decoration_single_punctate', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('decoration_comb_punctate', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('decoration_dentate', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('decoration_single_incised', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('decoration_comb_incised', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('decoration_applique', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('decoration_exposed_coil', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('decoration_carved', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('decoration_paint', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('decoration_redslip', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('decoration_finger', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('decoration_sculpt', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('decoration_paddle', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('decoration_lip', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('decoration_neck', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('decoration_whole', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('rim_direct', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('rim_direct_out', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('rim_direct_in', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('rim_incurving', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('rim_outcurving', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('rim_everted', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('rim_inverted', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('lip_gradual_in', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('lip_gradual_out', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('lip_abrupt', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('lip_bulge_in', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('lip_bulge_out', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('lip_bulge_both', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('handle', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('U', 'unknown')], default='U', max_length=7)),
                ('refs', models.ManyToManyField(blank=True, related_name='vessels', to='vessels.report')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=20, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('geonames_id', models.IntegerField(blank=True, null=True)),
                ('open_location_code', models.CharField(blank=True, max_length=100, null=True)),
                ('vessel', models.ManyToManyField(blank=True, related_name='area', to='vessels.vessel')),
            ],
        ),
    ]
