# Generated by Django 5.0.8 on 2024-08-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='traded',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='decoration_applique',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='decoration_carved',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='decoration_comb_incised',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='decoration_comb_punctate',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='decoration_dentate',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='decoration_exposed_coil',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='decoration_finger',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='decoration_lip',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='decoration_neck',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='decoration_paddle',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='decoration_paint',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='decoration_plain',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='decoration_redslip',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='decoration_sculpt',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='decoration_single_incised',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='decoration_single_punctate',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='decoration_whole',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='handle',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='lip_abrupt',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='lip_bulge_both',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='lip_bulge_in',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='lip_bulge_out',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='lip_gradual_in',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='lip_gradual_out',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='rim_direct',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='rim_direct_in',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='rim_direct_out',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='rim_everted',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='rim_incurving',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='rim_inverted',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='rim_outcurving',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='rim_technique',
            field=models.CharField(choices=[('C', 'coil'), ('CS', 'coil-spiral'), ('CR', 'coil-ring'), ('S', 'slab'), ('M', 'molded'), ('W', 'wheel'), ('O', 'other'), ('U', 'unknown')], default='U', max_length=20),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='use',
            field=models.CharField(choices=[('B', 'boiling'), ('F', 'frying'), ('FO', 'forno'), ('SE', 'serving'), ('ST', 'storage'), ('SM', 'smoking'), ('C', 'ceremonial'), ('O', 'other'), ('U', 'unknown')], default='U', max_length=20),
        ),
    ]
