# Generated by Django 5.0.8 on 2024-08-13 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0002_vessel_traded_alter_vessel_decoration_applique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitegroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vesselgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='')),
                ('name', models.CharField(max_length=100)),
                ('time_start', models.IntegerField(blank=True, null=True)),
                ('time_end', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='vessel',
            name='decoration_fingerdrag',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AddField(
            model_name='vessel',
            name='decoration_shell_punctate',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AddField(
            model_name='vessel',
            name='has_flat_base',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AddField(
            model_name='vessel',
            name='has_neck',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AddField(
            model_name='vessel',
            name='has_pointed_base',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.AddField(
            model_name='vessel',
            name='has_round_base',
            field=models.CharField(choices=[('P', 'present'), ('D', 'dominant'), ('C', 'common'), ('O', 'occasional'), ('R', 'rare'), ('A', 'absent'), ('U', 'unknown')], default='U', max_length=7),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=20, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('geonames_id', models.IntegerField(blank=True, null=True)),
                ('open_location_code', models.CharField(blank=True, max_length=100, null=True)),
                ('vessel', models.ManyToManyField(blank=True, related_name='site', to='vessels.vessel')),
                ('sitegroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='vessels.sitegroup')),
            ],
        ),
        migrations.AddField(
            model_name='vessel',
            name='vesselgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vessels', to='vessels.vesselgroup'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
