# Generated by Django 5.0.8 on 2024-08-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0003_sitegroup_vesselgroup_vessel_decoration_fingerdrag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='imagename',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
