# Generated by Django 5.0.8 on 2024-08-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0004_vessel_imagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='region',
            field=models.CharField(choices=[('MAR', 'Marianas'), ('CAR', 'Carolines'), ('BIS', 'Bismarck'), ('PNG', 'PNG'), ('SOL', 'Solomons'), ('VAN', 'Vanuatu'), ('MAL', 'Maluku'), ('NCA', 'New Caledonia'), ('FIJ', 'Fiji'), ('SAM', 'Samoa'), ('TON', 'Tonga'), ('MAQ', 'Marquesa'), ('NME', 'NE Melanesia'), ('COO', 'Cook'), ('TUV', 'Tuvalu'), ('U', 'unknown')], default='U', max_length=20),
        ),
    ]
