# Generated by Django 5.0.8 on 2024-08-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0005_alter_vessel_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='vesselgroup',
            name='sitegroup',
            field=models.ManyToManyField(blank=True, related_name='vesselgroups', to='vessels.sitegroup'),
        ),
        migrations.AlterField(
            model_name='site',
            name='region',
            field=models.CharField(choices=[('MAR', 'Marianas'), ('CAR', 'Carolines'), ('BIS', 'Bismarck'), ('PNG', 'PNG'), ('SOL', 'Solomons'), ('VAN', 'Vanuatu'), ('MAL', 'Maluku'), ('NCA', 'New Caledonia'), ('FIJ', 'Fiji'), ('SAM', 'Samoa'), ('TON', 'Tonga'), ('MAQ', 'Marquesa'), ('NME', 'NE Melanesia'), ('COO', 'Cook'), ('TUV', 'Tuvalu'), ('U', 'unknown')], default='U', max_length=20),
        ),
        migrations.RemoveField(
            model_name='site',
            name='sitegroup',
        ),
        migrations.AddField(
            model_name='site',
            name='sitegroup',
            field=models.ManyToManyField(blank=True, related_name='sites', to='vessels.sitegroup'),
        ),
    ]
