# Generated by Django 5.0.8 on 2024-08-14 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0006_vesselgroup_sitegroup_alter_site_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='imagename_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagename', to='vessels.report'),
        ),
        migrations.AddField(
            model_name='vesselgroup',
            name='time_end_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vg_time_end', to='vessels.report'),
        ),
        migrations.AddField(
            model_name='vesselgroup',
            name='time_start_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vg_time_start', to='vessels.report'),
        ),
    ]
