# Generated by Django 5.0.8 on 2024-08-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0007_vessel_imagename_ref_vesselgroup_time_end_ref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='vesselgroup',
        ),
        migrations.AddField(
            model_name='vessel',
            name='vesselgroup',
            field=models.ManyToManyField(blank=True, related_name='vessels', to='vessels.vesselgroup'),
        ),
    ]
