# Generated by Django 5.0.8 on 2024-08-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0009_rename_lip_bulge_in_vessel_lip_bulge_inside_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('type', models.CharField(choices=[('DEC', 'decoration'), ('MISC', 'misecellaneous')], default='MISC', max_length=5)),
                ('refs', models.ManyToManyField(blank=True, related_name='tags', to='vessels.report')),
            ],
        ),
        migrations.AddField(
            model_name='vessel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='vessels', to='vessels.tags'),
        ),
    ]
