# Generated by Django 5.0.8 on 2024-08-18 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0010_tags_vessel_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
