# Generated by Django 5.1.5 on 2025-01-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0011_rename_tags_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='production_site',
            field=models.BooleanField(default=False),
        ),
    ]
