# Generated by Django 5.1.5 on 2025-01-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0013_site_import_vessel'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='details',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
