# Generated by Django 5.1.5 on 2025-01-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0014_site_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='comments',
        ),
        migrations.AddField(
            model_name='sitegroup',
            name='details',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='details',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='vesselgroup',
            name='details',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
