# Generated by Django 5.1.5 on 2025-01-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0015_remove_vessel_comments_sitegroup_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vesselgroup',
            name='refs',
            field=models.ManyToManyField(blank=True, related_name='vesselgroups', to='vessels.report'),
        ),
    ]
