# Generated by Django 5.1.5 on 2025-01-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0016_vesselgroup_refs'),
    ]

    operations = [
        migrations.AddField(
            model_name='vesselgroup',
            name='vesgroup',
            field=models.ManyToManyField(blank=True, related_name='vgs', to='vessels.vesselgroup'),
        ),
    ]
