# Generated by Django 5.1.5 on 2025-01-23 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0017_vesselgroup_vesgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vesselgroup',
            name='vesgroup',
        ),
    ]
