# Generated by Django 5.1.5 on 2025-01-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0018_remove_vesselgroup_vesgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='vesselgroup',
            name='vg',
            field=models.ManyToManyField(to='vessels.vesselgroup'),
        ),
    ]
