# Generated by Django 5.1.5 on 2025-01-23 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0020_alter_vesselgroup_vg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='imagename',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='imagename_ref',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='traded',
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('refs', models.ManyToManyField(blank=True, related_name='feature', to='vessels.report')),
            ],
        ),
        migrations.AddField(
            model_name='vessel',
            name='feature',
            field=models.ManyToManyField(blank=True, related_name='vessels', to='vessels.feature'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='')),
                ('name', models.CharField(max_length=100)),
                ('imageloc', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, max_length=1000, null=True)),
                ('ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='vessels.report')),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='feature', to='vessels.image'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='vessels', to='vessels.image'),
        ),
        migrations.AddField(
            model_name='vesselgroup',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='vesselgroups', to='vessels.image'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
