# Generated by Django 5.1.5 on 2025-02-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0023_remove_vessel_decoration_applique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='form',
        ),
        migrations.AddField(
            model_name='feature',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='type',
            field=models.CharField(choices=[('M', 'morphology'), ('R', 'rim morphology'), ('D', 'decoration'), ('P', 'decorated area'), ('U', 'use')], default='M', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='legend',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
