# Generated by Django 5.1.5 on 2025-02-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0024_remove_vessel_form_feature_tag_feature_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='feature',
        ),
        migrations.AddField(
            model_name='vessel',
            name='common_feature',
            field=models.ManyToManyField(blank=True, related_name='vessels_common', to='vessels.feature'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='typical_feature',
            field=models.ManyToManyField(blank=True, related_name='vessels_typical', to='vessels.feature'),
        ),
    ]
