# Generated by Django 5.1.5 on 2025-02-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0026_vessel_base_technique_vessel_primary_technique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='base_technique',
            field=models.CharField(choices=[('B', 'ball'), ('S', 'spiral'), ('SL', 'slab'), ('P', 'pinching'), ('ST', 'strip'), ('O', 'other'), ('U', 'unknown')], default='U', max_length=20),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='primary_technique',
            field=models.CharField(choices=[('C', 'coil'), ('CS', 'coil-spiral'), ('CR', 'coil-ring'), ('S', 'slab'), ('P', 'pinching'), ('M', 'molded'), ('W', 'wheel'), ('O', 'other'), ('U', 'unknown')], default='U', max_length=20),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='rim_technique',
            field=models.CharField(choices=[('C', 'coil'), ('CS', 'coil-spiral'), ('CR', 'coil-ring'), ('S', 'slab'), ('P', 'pinching'), ('M', 'molded'), ('W', 'wheel'), ('O', 'other'), ('U', 'unknown')], default='U', max_length=20),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='secondary_technique',
            field=models.CharField(choices=[('B', 'beating'), ('PA', 'paddle and anvil'), ('N', 'none'), ('O', 'other'), ('U', 'unknown')], default='U', max_length=20),
        ),
    ]
