# Generated by Django 5.1.5 on 2025-02-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0027_alter_vessel_base_technique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('fullname', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='vessel',
            name='temper',
            field=models.BooleanField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='fabric',
            field=models.ManyToManyField(blank=True, related_name='vessels', to='vessels.fabric'),
        ),
    ]
