# Generated by Django 5.1.5 on 2025-02-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0030_rename_vg_vesselgroup_vg_parent_alter_vessel_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='import_vesselgroup',
            field=models.ManyToManyField(blank=True, related_name='isite', to='vessels.vesselgroup'),
        ),
        migrations.AddField(
            model_name='site',
            name='vesselgroup',
            field=models.ManyToManyField(blank=True, related_name='site', to='vessels.vesselgroup'),
        ),
        migrations.AddField(
            model_name='vesselgroup',
            name='fabric',
            field=models.ManyToManyField(blank=True, related_name='vesselgroups', to='vessels.fabric'),
        ),
    ]
