# Generated by Django 5.1.5 on 2025-02-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0031_site_import_vesselgroup_site_vesselgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='maptag',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
