# Generated by Django 5.1.5 on 2025-03-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0033_alter_vessel_gender_decorate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='base_technique',
            field=models.CharField(choices=[('ball', 'ball'), ('spiral', 'spiral'), ('slab', 'slab'), ('pinching', 'pinching'), ('strip', 'strip'), ('other', 'other'), ('unknown', 'unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='primary_technique',
            field=models.CharField(choices=[('coil', 'coil'), ('coil-spiral', 'coil-spiral'), ('coil-ring', 'coil-ring'), ('slab', 'slab'), ('pinching', 'pinching'), ('molded', 'molded'), ('wheel', 'wheel'), ('other', 'other'), ('unknown', 'unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='rim_technique',
            field=models.CharField(choices=[('coil', 'coil'), ('coil-spiral', 'coil-spiral'), ('coil-ring', 'coil-ring'), ('slab', 'slab'), ('pinching', 'pinching'), ('molded', 'molded'), ('wheel', 'wheel'), ('other', 'other'), ('unknown', 'unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='secondary_technique',
            field=models.CharField(choices=[('beating', 'beating'), ('paddle and anvil', 'paddle and anvil'), ('none', 'none'), ('other', 'other'), ('unknown', 'unknown')], default='unknown', max_length=20),
        ),
    ]
