# Generated by Django 5.1.5 on 2025-03-21 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0034_alter_vessel_base_technique_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vessel',
            old_name='common_feature',
            new_name='occasional_feature',
        ),
    ]
