# Generated by Django 5.1.5 on 2025-03-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0035_rename_common_feature_vessel_occasional_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='primary_technique',
            field=models.CharField(choices=[('coil', 'coil'), ('coil-spiral', 'coil-spiral'), ('coil-ring', 'coil-ring'), ('slab', 'slab'), ('pinching', 'pinching'), ('molded', 'molded'), ('hammering', 'hammering'), ('wheel', 'wheel'), ('other', 'other'), ('unknown', 'unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='rim_technique',
            field=models.CharField(choices=[('coil', 'coil'), ('coil-spiral', 'coil-spiral'), ('coil-ring', 'coil-ring'), ('slab', 'slab'), ('pinching', 'pinching'), ('molded', 'molded'), ('hammering', 'hammering'), ('wheel', 'wheel'), ('other', 'other'), ('unknown', 'unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='secondary_technique',
            field=models.CharField(choices=[('beating', 'beating'), ('paddle and anvil', 'paddle and anvil'), ('scraping', 'scraping'), ('other', 'other'), ('unknown', 'unknown')], default='unknown', max_length=20),
        ),
    ]
