# Generated by Django 5.1.5 on 2025-03-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0036_alter_vessel_primary_technique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='base_technique',
            field=models.CharField(choices=[('ball', 'ball'), ('spiral', 'spiral'), ('slab', 'slab'), ('other', 'other'), ('unknown', 'unknown')], default='unknown', max_length=20),
        ),
    ]
