# Generated by Django 5.1.5 on 2025-03-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0037_alter_vessel_base_technique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='primary_technique',
            field=models.CharField(choices=[('coil', 'coil'), ('coil-spiral', 'coil-spiral'), ('coil-ring', 'coil-ring'), ('slab', 'slab'), ('pinching', 'pinching'), ('moulded', 'moulded'), ('hammering', 'hammering'), ('wheel', 'wheel'), ('other', 'other'), ('unknown', 'unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='rim_technique',
            field=models.CharField(choices=[('coil', 'coil'), ('coil-spiral', 'coil-spiral'), ('coil-ring', 'coil-ring'), ('slab', 'slab'), ('pinching', 'pinching'), ('moulded', 'moulded'), ('hammering', 'hammering'), ('wheel', 'wheel'), ('other', 'other'), ('unknown', 'unknown')], default='unknown', max_length=20),
        ),
    ]
