# Generated by Django 5.1.5 on 2025-03-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0038_alter_vessel_primary_technique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='all_feature',
            field=models.ManyToManyField(blank=True, related_name='vessels_all', to='vessels.feature'),
        ),
        migrations.AlterField(
            model_name='vesselgroup',
            name='vg_parent',
            field=models.ManyToManyField(blank=True, to='vessels.vesselgroup'),
        ),
    ]
