# Generated by Django 5.1.5 on 2025-03-25 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0039_vessel_all_feature_alter_vesselgroup_vg_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='all_feature',
        ),
        migrations.AddField(
            model_name='vessel',
            name='use_baking',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='vessel',
            name='use_boiling',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='vessel',
            name='use_burial',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='vessel',
            name='use_ceremonial',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='vessel',
            name='use_cooking',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='vessel',
            name='use_eating',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='vessel',
            name='use_frying',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='vessel',
            name='use_hearth',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='vessel',
            name='use_lid',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='vessel',
            name='use_light',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='vessel',
            name='use_musical_instrument',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='vessel',
            name='use_serving',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='vessel',
            name='use_smoking',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='vessel',
            name='use_storage',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
