# Generated by Django 5.1.5 on 2025-03-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0043_vessel_dec_applique_vessel_dec_bands_vessel_dec_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
