# Generated by Django 5.1.5 on 2025-06-03 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0045_remove_vesselgroup_sitegroup_remove_site_sitegroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='morph_stand',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
